AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with optional versioning

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket ok
  VersioningState:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Suspended
    Description: Set versioning state (Enabled or Suspended)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningState

Outputs:
  BucketNameOutput:
    Description: Name of the created S3 bucket
    Value: !Ref BucketName
